/* FIREBASE_PROJECT_ID: string;
FIREBASE_CLIENT_EMAIL: string;

AUTH_GOOGLE_ID: string;
AUTH_GOOGLE_SECRET: string;

AUTH_SECRET: string;

STRIPE_PRICE_ID: string;
STRIPE_SUBSCRIPTION_ID: string;
STRIPE_SECRET_KEY: string;
STRIPE_WEBHOOK_SECRET: string;
NEXT_PUBLIC_STRIPE_PUBLIC_KEY: string; */
